#!/usr/bin/env python3
"""Write an LLM-generated summary for every commit that changes a prompt.

A commit qualifies when it modifies (not creates) a per-model file such as
claude-haiku-4-5.md or a per-family file such as claude-opus.md, because
those diffs show a prompt changing from one revision or model to the next.
Dated files are only ever created, so they never qualify.

Each summary is written to _summary/<full commit sha>.md and contains only
the bullet list produced by the model, so it can be embedded elsewhere.

When a revision's per-model diff and per-family diff are identical (the
previous prompt in the family was an earlier revision of the same model),
only the per-family commit is summarized; `canonical_sha` on the per-model
change points at it.

Summaries are generated by piping the diff and both full prompts into the
`llm` CLI (https://llm.datasette.io/), using the model named in MODEL.

Usage:
    python3 summarize_commits.py             # summarize commits that lack one
    python3 summarize_commits.py --dry-run   # list what would be summarized
    python3 summarize_commits.py --limit 3   # stop after three summaries
    python3 summarize_commits.py --sha X     # (re)generate one commit's summary
"""

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PROMPTS_DIR = ROOT / "prompts"
SUMMARY_DIR = ROOT / "_summary"
MODEL = "gpt-5.6-luna"

DATED_RE = re.compile(r"^claude-.*-\d{4}-\d{2}-\d{2}\.md$")
FAMILY_RE = re.compile(r"^claude-[a-z]+\.md$")
HEADER_RE = re.compile(r"^# (.+?) — (.+)$")

PROMPT = """\
You are summarizing one commit in a git repository that tracks the system prompts Anthropic publishes for Claude on claude.ai. The diff shows how the prompt changed from the previous model or revision to this one, using word-level markers: [-removed-] and {+added+}. The diff is followed by the full text of the previous prompt and of the new prompt; use them to check whether something that looks added in the diff already existed before.

Pick out only the most interesting changes: new rules or behaviors, rules that were dropped or loosened, anything surprising, and anything that reveals a new policy or product direction. Skip routine changes that every new prompt makes: updated model names and IDs, the knowledge cutoff date, product lists, settings lists, typo fixes, and rewordings that do not change meaning.

Read the diff carefully. Text marked {+added+} right next to text marked [-removed-] is usually a rewording of the same rule, not a new rule; compare the two before calling anything new. It is better to report nothing than to report a rewording as a change.

Rules:
- Output 1-5 bullets and nothing else. No introduction, no headings, no closing line.
- Each bullet is one sentence of at most about 25 words. Most interesting change first.
- Quote a short phrase from the prompt when that is the sharpest way to show the change.
- If nothing substantive changed, output a single bullet that says so and names the routine changes in a few words.
- Only describe what is in the diff. Do not speculate about motives.
- Plain, direct language. No hype, no emoji.
"""


def git(*args):
    return subprocess.run(
        ["git", *args], cwd=ROOT, check=True, capture_output=True, text=True
    ).stdout


@dataclass
class Change:
    sha: str
    short: str
    date: str          # YYYY-MM-DD from the commit date
    path: str          # file the commit modifies, e.g. prompts/claude-opus.md
    kind: str          # "family" or "model"
    descriptor: str    # "Claude Fable 5.1 — September 1, 2026"
    prev_title: str    # "Claude Fable 5 — June 9, 2026", from the old file header
    new_title: str
    canonical_sha: str # sha whose summary applies to this change

    @property
    def summary_path(self):
        return SUMMARY_DIR / f"{self.canonical_sha}.md"

    def summary(self):
        if self.summary_path.exists():
            return self.summary_path.read_text(encoding="utf-8").strip()
        return None


def header_title(sha, path):
    first = git("show", f"{sha}:{path}").split("\n", 1)[0]
    m = HEADER_RE.match(first)
    return f"{m.group(1)} — {m.group(2)}" if m else first.lstrip("# ")


def list_changes():
    """Every qualifying commit, newest first, with duplicates resolved."""
    rolling = sorted(
        p.name for p in PROMPTS_DIR.glob("claude-*.md") if not DATED_RE.match(p.name)
    )
    changes = []
    for name in rolling:
        path = f"prompts/{name}"
        kind = "family" if FAMILY_RE.match(name) else "model"
        log = git("log", "--diff-filter=M", "--format=%H%x00%h%x00%ad%x00%s",
                  "--date=short", "--", path)
        for line in log.splitlines():
            sha, short, date, subject = line.split("\x00")
            prefix = f"{name}: "
            descriptor = subject[len(prefix):] if subject.startswith(prefix) else subject
            changes.append(Change(
                sha=sha, short=short, date=date, path=path, kind=kind,
                descriptor=descriptor,
                prev_title=header_title(f"{sha}^", path),
                new_title=header_title(sha, path),
                canonical_sha=sha,
            ))

    # A per-model change duplicates the per-family change for the same
    # revision when both start from the same previous text.
    families = {c.descriptor: c for c in changes if c.kind == "family"}
    for c in changes:
        if c.kind != "model":
            continue
        fam = families.get(c.descriptor)
        if fam is None:
            continue
        if git("rev-parse", f"{c.sha}^:{c.path}") == git("rev-parse", f"{fam.sha}^:{fam.path}"):
            c.canonical_sha = fam.sha

    changes.sort(key=lambda c: c.date, reverse=True)
    return changes


def llm_input(change):
    diff = git("show", "--word-diff=plain", f"--format=Commit: %s%n",
               change.sha, "--", change.path)
    old = git("show", f"{change.sha}^:{change.path}")
    new = git("show", f"{change.sha}:{change.path}")
    return (
        f"{diff}\n\n=== FULL TEXT OF PREVIOUS PROMPT ===\n{old}\n\n"
        f"=== FULL TEXT OF NEW PROMPT ===\n{new}"
    )


def summarize(change):
    result = subprocess.run(
        ["llm", "-m", MODEL, "--no-stream", "-s", PROMPT],
        input=llm_input(change), capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"llm failed for {change.short}: {result.stderr.strip()}")
    text = result.stdout.strip()
    if not text.startswith("-"):
        raise RuntimeError(f"unexpected llm output for {change.short}: {text[:200]!r}")
    SUMMARY_DIR.mkdir(exist_ok=True)
    (SUMMARY_DIR / f"{change.sha}.md").write_text(text + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--dry-run", action="store_true", help="list commits needing summaries")
    parser.add_argument("--limit", type=int, help="stop after this many summaries")
    parser.add_argument("--sha", help="(re)generate the summary for one commit")
    args = parser.parse_args()

    changes = list_changes()
    if args.sha:
        todo = [c for c in changes if c.sha.startswith(args.sha) and c.canonical_sha == c.sha]
        if not todo:
            sys.exit(f"No summarizable commit matches {args.sha}")
    else:
        todo = [c for c in changes if c.canonical_sha == c.sha and not c.summary_path.exists()]

    if not todo:
        print("Nothing to do: every qualifying commit has a summary.")
        return 0

    done = 0
    for c in todo:
        print(f"{c.short} {c.date}  {c.path}: {c.prev_title}  ->  {c.new_title}", flush=True)
        if args.dry_run:
            continue
        summarize(c)
        done += 1
        if args.limit and done >= args.limit:
            break
    print(f"{'Would generate' if args.dry_run else 'Generated'} {len(todo) if args.dry_run else done} summar{'y' if done == 1 else 'ies'}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
